### ISSUE TITLE
Feature request: Setting per workflow custom reorg applet

### ISSUE THREAD

**Issue by dolevrahat** [dnanexus/dxCompiler#180]
Hello

I am developing a workflow that has several sub-workflow.
I wish to set a custom reorg applet for one the sub-workflows (which is imported from a separate WDL file). 
I tried accomplishing this by setting the `perWorkflowDxAttributes` in the extras file, namely:
```
 "perWorkflowDxAttributes":{
	"mapping_variation_annotation_v16_mt_IDT":{
	"customReorgAttributes" : {
    	"appUri" : "applet-G4vx2q80GjFY4KFy7vp4ykkK",
    	"configFile" : "dx://project-G436vv80GjFz96PfFqxF92Kf:file-G4pypqQ0GjFvYXB2KxzKVbxx"
  	}	
	}
  }
```
However, when I compiled the workflow with the extras file, the custom reorg applet  was ignored, and instead the subworkflow mapping_variation_annotation_v16_mt_IDT used the default reorg applet.
Is there a way to accomplish what I'm trying to do?
When I try to set the custom reorg applet as an attribute of the entire workflow (i.e. not placing the `customReorgAttributes` bloc within the `perWorkflowDxAttributes`), it is assigned to the top-level workflow, and the sub-workflows are compiled without a reorg stage. This solution is not ideal for me because the sub-workflow mapping_variation_annotation_v16_mt_IDT is intended to be called by a scatter of the top-level workflow, and the outputs from each call to mapping_variation_annotation_v16_mt_IDT are intended to be place in a different folder in the project.

Thanks in advance!!

**Comment by commandlinegirl** [comment]
Hi Dolev! Thank you for the suggestion. I opened a ticket for tracking this internally. We'll look into this and will get back to you!

**Comment by commandlinegirl** [comment]
Hi Dolev! It's currently possible to set the reorg applet only at the top-level. At the moment we won't have bandwidth to implement and maintain the per-workflow setting you describe. We have the request in our system and will leave it open for future consideration to implement together with other custom reorg features. Thank you.
