### ISSUE TITLE
Task with stubbed applet as runtime does not obey instance type

### ISSUE THREAD

**Issue by Ben-Habermeyer** [dnanexus/dxCompiler#406]
Hi dxCompiler team; I am looking to call an existing applet in WDL as part of a larger workflow, and specify the instance to use based on input size. 

I see some examples in the unit tests https://github.com/dnanexus/dxCompiler/commit/28e3f7f718fad7307daf5be947862523b2fcb5d5 but following the example got an unexpected result

```
task myriad_bcl2fastq220 {
      input {
        String? rerun_nonce
        Array[File] run_archive
        String? advanced_opts
        Boolean? no_lane_splitting
        Boolean? create_empty_fastqs
        Int? upload_parallelism
        File? sample_sheet
      }
      command {}
      output {
        Array[File]+ stats = ["dummy.txt"]
        Array[File]+ demux_summaries = ["dummy.txt"]
        Array[File]+ fastq_summaries = ["dummy.txt"]
        File interop_run_tar = "dummy.txt"
        Array[File] undetermined_reads = []
        Array[File]+ reads = ["dummy.txt"]
        File run_log = "dummy.txt"
        Array[File] reads2 = []
      }
      runtime {
        # choose large bandwidth instance if s4 flowcell
        dx_instance_type: if size(run_archive, "GB") > 200 then "mem3_ssd3_x96" else "mem1_ssd1_v2_x72"
        dx_app: object {
            type: "applet",
            id: "applet-GK3BQz80jf5258Z175B26xgV",  # app: myriad-bcl2fastq220 with retry
            name: "myriad-bcl2fastq220"
        }
      }
}
```

At runtime this job continues to use the default app instance https://platform.dnanexus.com/projects/FyJQfy80jf50JG4xGXxF2bgq/monitor/job/GKFfFx80jf5FzKx239VB5gkg and also is not proper WDL syntax 

```
(demux.wdl Ln 66 Col 17) Expected String instead of object(id : String, name : String, type : String)
            dx_app: object {
                    ^^^^^^^^
```

How may I specify an existing app/applet but override the instance / compute parameters?

**Comment by Gvaihir** [comment]
Hi!
Instance types can be set like [here](https://github.com/dnanexus/dxCompiler/blob/develop/doc/ExpertOptions.md#task-runtime-and-hints). Expects a string.
Ternary operator syntax looks [like this](https://github.com/openwdl/wdl/blob/main/versions/1.1/SPEC.md#ternary-operator-if-then-else). 
Supported instance type override methods for native apps are [here](https://github.com/dnanexus/dxCompiler/blob/develop/doc/Internals.md#support-for-native-dnanexus-executables)

**Comment by Ben-Habermeyer** [comment]
@Gvaihir the following doesn't seem to generate the app fragment with the conditional "body" just uses the instance in the applet. Can you elaborate a bit more on the following supported feature? does this mean I cannot do a conditional, but rather can only override with static option?

Fragment | Static | Instance name | ✓ | Implemented in v2.10.2-SNAPSHOT
-- | -- | -- | -- | --


```
task myriad_bcl2fastq220 {
      input {
        String? rerun_nonce
        Array[File] run_archive
        String? advanced_opts
        Boolean? no_lane_splitting
        Boolean? create_empty_fastqs
        Int? upload_parallelism
        File? sample_sheet
      }
      command {}
      output {
        Array[File]+ stats = ["dummy.txt"]
        Array[File]+ demux_summaries = ["dummy.txt"]
        Array[File]+ fastq_summaries = ["dummy.txt"]
        File interop_run_tar = "dummy.txt"
        Array[File] undetermined_reads = []
        Array[File]+ reads = ["dummy.txt"]
        File run_log = "dummy.txt"
        Array[File] reads2 = []
      }
    runtime {
        dx_instance_type: if size(run_archive, "GB") > 150 then "mem3_ssd3_x96" else "mem1_ssd1_v2_x72"
    }
    meta {
     type : "native"
     id : "applet-GKFv6J80jf56pQJq5jbP55Gz"  # app: myriad-bcl2fastq220 with retry
    }
}
```

**Comment by Gvaihir** [comment]
Of course!
Which value for `instanceTypeSelection` are you using when compiling the WF?
If you are compiling with `instanceTypeSelection` set to `static` - this should not work because `static` runtime should be defined at compile time (hence "static"). However as of now, `dynamic` instance type selection is not supported for pre-built (aka native) apps.
Links to ternary operator syntax - just to be sure `dx_instance_type` receives a `String` type.

**Comment by Ben-Habermeyer** [comment]
ok I see thanks. I think we are using "dynamic" as we are not specifying it and use this conditional syntax elsewhere in the WDL

**Comment by Gvaihir** [comment]
sure, just keep in mind - `static` is the default
