### ISSUE TITLE
[error] You must be logged in to compile using mode All

### ISSUE THREAD

**Issue by OmegaPetrazzini** [dnanexus/dxCompiler#438]
Hello, 

I am trying to compile a SAIGE workflow following these instructions: https://saigegit.github.io/SAIGE-doc/docs/UK_Biobank_WES_analysis.html#prerequisites.

I keep on getting this error when trying to compile the workflow: [error] You must be logged in to compile using mode All.

I am fully logged in to my project, I am able to download/upload files and send swiss-army-knife jobs.

This is the code I am running from my university HPC:
java -jar dxCompiler-2.11.0.jar compile saige_step1_spGRMforNULLModel.wdl -project project-G54K68jJxz3BKpkb0fF7fvvf -folder /workflows/ -f -verbose -logFile run.out

And this is how I defined the docker image path in the saige_null_sGRM_vr_withinfo.wdl file:
docker: "dx://project-G54K68jJxz3BKpkb0fF7fvvf:/GWAS_CAD/associations/ukb/SAIGE/docker_images/saige_1.1.6.3.tar.gz"

Do you have any dea what might be going on?

Thanks much in advance and have a great day!
Ben

**Comment by Gvaihir** [comment]
How did you login?

**Comment by OmegaPetrazzini** [comment]
Hi Gvaihir,

I logged in using the following code on my university HPC:

ml dx-toolkit
source $DNANEXUS_HOME/environment 
ml proxies
dx login

**Comment by Gvaihir** [comment]
Do you switch shells after login?
Could you `dx env` - don't forget to mask the tokens before pasting here

**Comment by OmegaPetrazzini** [comment]
I believe I am not switching shells. I can continue working from my university HPC as usual, but then also interact with RAP using the dx command.

Here's the env:
[myID@HPC_node gene_burden]$ dx env
Auth token used		number
API server protocol	https
API server host		api.dnanexus.com
API server port		443
Current workspace	project-number
Current workspace name	"PI Laboratory"
Current folder		/
Current user		benomega.petrazzini

Thank you for your help!

**Comment by Gvaihir** [comment]
> I can continue working from my university HPC as usual, but then also interact with RAP using the dx command

I don't understand how HPC relates to the DNAnexus platform in your setup. I have a feeling you login on one shell (maybe local?) and compile the workflow from another shell (HPC?). Make sure you don't change the environment and compile the workflow in the same shell where you run `dx login`.  
If you do 
```
dx login
java -jar dxCompiler-2.11.0.jar compile ...
```
and still see this error - contact the support, there's something with your credentials
