### ISSUE TITLE
UK Biobank RAP path with spaces in it

### ISSUE THREAD

**Issue by nshrine** [dnanexus/dxCompiler#454]
How do I get dxCompiler to accept a path with spaces in it? e.g.

Array[File]+ bgens = ["dx://project-GJbvyPjJy3Gy01jz4x8bXzgv:/Bulk/Imputation/UKB imputation from genotype/ukb22828_c10_b0_v3.bgen","dx://project-GJbvyPjJy3Gy01jz4x8bXzgv:/Bulk/Imputation/UKB imputation from genotype/ukb22828_c6_b0_v3.bgen",

Below doesn't work nor does one \ or 4 \\\\

Array[File]+ bgens = ["dx://project-GJbvyPjJy3Gy01jz4x8bXzgv:/Bulk/Imputation/UKB\\ imputation\\ from\\ genotype/ukb22828_c10_b0_v3.bgen","dx://project-GJbvyPjJy3Gy01jz4x8bXzgv:/Bulk/Imputation/UKB\\ imputation\\ from\\ genotype/ukb22828_c6_b0_v3.bgen"]

**Comment by Gvaihir** [comment]
Where does it break - compile time or runtime? And add the error stack trace please.

**Comment by nshrine** [comment]
> Where does it break - compile time or runtime? And add the error stack trace please.

At compile time, and I have fixed it, you just need to use "%20" instead of spaces i.e.:

Array[File]+ bgens = ["dx://project-GJbvyPjJy3Gy01jz4x8bXzgv:/Bulk/Imputation/UKB%20imputation%20from%20genotype/ukb22828_c10_b0_v3.bgen","dx://project-GJbvyPjJy3Gy01jz4x8bXzgv:/Bulk/Imputation/UKB%20imputation%20from%20genotype/ukb22828_c6_b0_v3.bgen"]

**Comment by Gvaihir** [comment]
Good:)
