### ISSUE TITLE
Supporting WDL 1.0 "struct"

### ISSUE THREAD

**Issue by zhoulytwinyu** [dnanexus/dxCompiler#89]
dxCompiler 2.4.1 is not supporting "struct" properly, and gives error message during compiling. dxWDL 1.50 is on the other hand compiles successfully.

==============START OF ERROR MESSAGE================
[error] Error translating test-struct.wdl to IR
java.lang.Exception: input <sample_name, TString> to call <test> is missing from the environment. We don't have sampleStruct.sample_name in the environment.
...
==============END OF ERROR MESSAGE================

===============START OF WDL FILE =====================
version 1.0

task test {
  input {
    String sample_name
    Array[File] read_fastq_list
    Array[String] flowcell_id_list
  }
  
  command <<<
    set -ex
    
    mkdir fastq_dir
    while read flowcell_id fastq_file
      do mkdir ${flowcell_id}
      mv ${fastq_file} $flowcell
    done < <(paste ~{write_lines(flowcell_id_list)} ~{write_lines(read_fastq_list)})
    echo $(ls -R )
  >>>

  output {
    String out = read_string(stdout())
  }

  runtime {
    docker: "docker.io/scicomppublic/centos:7"
  }
}

struct SampleStruct {
  String sample_name
  Array[File] read_fastq_list
  Array[String] flowcell_id_list
}

workflow test_workflow {

  input {
    SampleStruct sampleStruct
  }
  
  call test_map_serialization {
    input:
      sample_name = sampleStruct.sample_name,
      read_fastq_list = sampleStruct.read_fastq_list,
      flowcell_id_list = sampleStruct.flowcell_id_list,
  }
  
  output {
    String out = test.out
  }
}
===============END OF FILE =====================

**Comment by emiloslavsky** [comment]
Thanks, we'll take a look at this.

**Comment by jdidion** [comment]
this issue is fixed and will be in the next release
